name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Deploy, build, and clean up on server
        run: |
          # sudo apt-get update && sudo apt-get install -y sshpass

          # SSH into the server and deploy
          sshpass -p "${{ secrets.VPS_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
          echo "Deploying the project"

          # Create the directory if it doesn't exist
          mkdir -p ~/work/OscarsBE

          # Navigate to the directory
          cd ~/work/OscarsBE

          # If the repository exists, pull the latest changes; otherwise, clone it
          if [ -d ".git" ]; then
            git pull origin master
          else
            git clone https://github.com/Karan1980/RTMS-Backend.git .
          fi

          # Install PM2 globally if not already installed
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 not found. Installing PM2..."
            sudo npm install -g pm2
          fi
          
          # Install dependencies and build the project
          npm install

          # Deploy the build to /var/www/ongc.rtms.foxboroinstrument/*
          sudo rm -rf /var/www/ongc.rtms.foxboroinstrument/*
          sudo cp -r ~/work/OscarsBE/* /var/www/ongc.rtms.foxboroinstrument/

          # Start the Node.js application using PM2
          # Check if the app is already running; if not, start it
          if pm2 list | grep -q 'ongc-rtms-backend'; then
            pm2 restart ongc-rtms-backend
          else
            pm2 start /var/www/ongc.rtms.foxboroinstrument/index.js --name ongc-rtms-backend # Adjust to your entry point file
          fi

          # Save PM2 process list and configuration
          pm2 save

          # Cleanup: Remove the ~/work/OscarsBE directory after deployment
          cd ~
          rm -rf ~/work/OscarsBE

          EOF